export const cities: Record<string, string[]> = {
  Brasil: [
    'São Paulo',
    'Rio de Janeiro',
    'Belo Horizonte',
    'Salvador',
    'Brasília',
    'Curitiba',
    'Fortaleza',
    'Recife',
    'Porto Alegre',
    'Manaus',
  ],
  Argentina: ['Buenos Aires', 'Córdoba', 'Rosário', 'Mendoza', 'Tucumán'],
  Chile: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'],
  Colômbia: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
  México: ['Cidade do México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'],
  Peru: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco'],
  Uruguai: ['Montevidéu', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera'],
  Paraguai: ['Assunção', 'Ciudad del Este', 'Encarnación', 'San Lorenzo', 'Capiatá'],
  Bolívia: ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'Oruro'],
  Equador: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala'],
  Venezuela: ['Caracas', 'Maracaibo', 'Valência', 'Barquisimeto', 'Maracay'],
  'Estados Unidos': ['Nova York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
  Canadá: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton'],
  Portugal: ['Lisboa', 'Porto', 'Braga', 'Coimbra', 'Funchal'],
  Espanha: ['Madrid', 'Barcelona', 'Valência', 'Sevilha', 'Zaragoza'],
};
